### ISSUE TITLE
Librairy to compile

### ISSUE THREAD

**Issue by RF-TEC** [s21rc/Arduino-LDMOS-SSPA-Controller-v1.3#1]
hello 

I would like to congratulate you on your work.

Beyond all considerations, wishing to proceed with the compilation, 
could you please indicate precisely the required libraries 
to be attached, as well as the links to obtain them.

Will these headers be sufficient or is there more code to include ?
```
<EEPROM.h>
<OneWire.h>
<DallasTemperature.h> //https://github.com/milesburton/Arduino-Temperature-Control-Library
<math.h> 
<EasyNextionLibrary.h> // https://github.com/Seithan/EasyNextionLibrary
```

Thanks for your support

**Comment by s21rc** [comment]
Hello,
EEPROM.h and math.h are builtin library comes with the IDE/Compiler. 
Load/Install the remaining library from library manager or from the link given in comment/below.

OneWire.h -  https://www.arduino.cc/reference/en/libraries/onewire/
<DallasTemperature.h - https://github.com/milesburton/Arduino-Temperature-Control-Library
<EasyNextionLibrary.h> -  https://github.com/Seithan/EasyNextionLibrary

Let me know how it goes. S21RC

**Comment by RF-TEC** [comment]
Thanks for your feedback

The following libraries are installed

OneWire
DallasTemperature
EasyNextionLibrary

But I encounter an basical error during compilation with the header <nrf.h> related to builtin EEPROM library

```
In file included from ../NVRAM.h:21:0,
                 from ../EEPROM.h:25,
                 from ../Arduino-LDMOS-SSPA-Controller-v1.4.ino:16:
../Flash.h:28:17: fatal error: nrf.h: No such file or directory
 #include <nrf.h>
```

Compilation is done with IDE VSM from Proteus ISIS Software and the present and functional libraries for Nano rev3.

What do you think?

Thanks
F4APX

**Comment by s21rc** [comment]
Hi Frederic,
I am not used to using proteus and simulation. The function of the EEPROM is to write the band when ever it get changed. So next time you turn on the system, it loads the last position from memory. For test purpose do bellow:

Pls  comment out all three line related to EEPROM.
and add  (current_band=1;) like below before line 758 in setup. This will set the current band to 1 when first time arduino runs. 

//EEPROM.get(0, current_band); // Load last band position to current_band variable from memory location 0
current_band=1;
lpf_relay(current_band);
display_band(current_band);
}

BTW: have you tried including the missing library said by the error code:

#include <nrf.h>

??

**Comment by RF-TEC** [comment]
Of course, well rated, now the current band is set to 1

```
EEPROM.get(0, current_band); // Load last band position to current_band variable from memory location 0
current_band=1;
lpf_relay(current_band);
display_band(current_band);
```

Effectively, i tried to include <nrf.h> from various sources, but i assume that the version included is not the correct one.

Also an hypothesis, the version of EEPROM library may not be up to date to support Nano rev 3.

Tnx

**Comment by s21rc** [comment]
nrf.h is not directly related to this code, maybe it's some kind of dependency of EEPROM.h for the simulation software you are using. In my computer there is no such file (search do not get anything).

And NRF is for a different chipset. make sure you selected Nano V3 with Atmel 328 microcontroller.

**Comment by RF-TEC** [comment]
Hello

Absolutely, this is an error related to the configuration of the project with the IDE integrated into Proteus, it is necessary to configure the project including the µC as soon as it is created and not to start from a blank page and configure during of compiling, this allows to include the required resources and to perform the configuration of the µC.

It should be fine

Thanking you for your support

I will inform you if you wish of the good progress and the follow-up given to the project,
and will gladly follow the evolution of your work on your repository.

Wishing you a nice day

Kind regards
73, Frédéric
F4APX
