### ISSUE TITLE
antenna 2

### ISSUE THREAD

**Issue by RF-TEC** [s21rc/Arduino-LDMOS-SSPA-Controller-v1.3#2]
Hi

By compiling under the Arduino IDE v1.8.19,  an error related to "antenna2" appeared.

I looked at the code, but I can't explain the reason, please would you know what it is?

```
Arduino-LDMOS-SSPA-Controller-v1.4:684:18: error: 'antenna2' was not declared in this scope
     digitalWrite(antenna2, HIGH);
```

**Comment by s21rc** [comment]
Sorry my bad (I commented that as I do not have 2 antennas), please uncomment the line 43:

//#define antenna2 10 //Antenna 2 relay pin of arduino

to:
#define antenna2 10 //Antenna 2 relay pin of arduino

**Comment by RF-TEC** [comment]
Hello, 

it's solved, everything is in order. 

Thanks.
